server:
  bind_addr: ":8088"
  dbg: false # enable debug mode, can be set to true with --dbg flag when running the service

# mqtt credentials
mqtt:
  mq_user: foo
  mq_password: bar
  mq_client_id: baz
  mq_broker_url: ssl://mqtt.foobar.com:8883
  mq_root_topic: "#"

# sqlite3 credentials
storage:
  type: sqlite
  path: file:./mqttdata.db?mode=rwc

#  type: bolt
#  database_url: /mnt/ramdisk/mqttdata.bolt

# raw sensor data could be expensive to store
collect_raw: false